# Generated by Django 3.2.9 on 2022-06-14 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='item',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='no_of_item',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='total_amount',
        ),
    ]
