# Generated by Django 3.2.9 on 2022-06-14 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220614_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
