# Generated by Django 3.2.9 on 2022-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='shop_no',
            field=models.IntegerField(null=True),
        ),
    ]
