# Generated by Django 3.2.9 on 2022-06-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('ordered_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditemsmodel',
            name='item',
        ),
        migrations.AddField(
            model_name='ordereditemsmodel',
            name='item',
            field=models.ManyToManyField(blank=True, to='item.ItemModel'),
        ),
    ]
