# Generated by Django 3.2.9 on 2022-06-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordered_item', '0002_auto_20220614_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedIemsItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ordereditems_item',
                'managed': False,
            },
        ),
    ]
