# Generated by Django 3.2.9 on 2022-06-14 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermodel_order_date'),
        ('ordered_item', '0003_orderediemsitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditemsmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel'),
        ),
    ]
