# Generated by Django 3.2.9 on 2022-06-14 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220614_1018'),
        ('order_detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detailmodel',
            old_name='no_of_item',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='order_detailmodel',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordermodel'),
        ),
    ]
