# Generated by Django 3.2.9 on 2022-06-14 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('order_detail', '0002_auto_20220614_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderdetailModel',
            fields=[
                ('orderdetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('created_by', models.IntegerField(default=1)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.itemmodel')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
        migrations.DeleteModel(
            name='Order_detailModel',
        ),
    ]
